#!/usr/bin/env python3
import json
import matplotlib.pyplot as plt
import os

FITNESS_HISTORY_PATH = "/home/ubuntu/pfoa_working_dir/pfoa_fitness_history.json"
OUTPUT_PLOT_PATH = "/home/ubuntu/pfoa_working_dir/fitness_over_generations.png"

def plot_fitness_history():
    print(f"Loading fitness history from {FITNESS_HISTORY_PATH}...")
    try:
        # Ensure the directory exists, as it might have been cleared by reset
        os.makedirs(os.path.dirname(OUTPUT_PLOT_PATH), exist_ok=True)
        with open(FITNESS_HISTORY_PATH, "r") as f:
            history = json.load(f)
    except FileNotFoundError:
        print(f"Error: Fitness history file not found at {FITNESS_HISTORY_PATH}. This file should have been generated by pfoa_core.py.")
        print("Please ensure pfoa_core.py was run successfully and the file exists.")
        return
    except Exception as e:
        print(f"Error loading fitness history: {e}")
        return

    if not history:
        print("Fitness history is empty. Cannot generate plot.")
        return

    generations = [item["generation"] for item in history]
    best_fitness_values = [item["best_fitness"] for item in history]

    print("Generating fitness plot...")
    plt.figure(figsize=(12, 7))
    plt.plot(generations, best_fitness_values, marker='o', linestyle='-')
    plt.title("Best Fitness per Generation (PFOA)", fontsize=16)
    plt.xlabel("Generation", fontsize=14)
    plt.ylabel("Best Fitness (Negative Penalty)", fontsize=14)
    plt.grid(True)
    plt.xticks(generations[::max(1, len(generations)//20)]) # Show a reasonable number of x-ticks
    
    if len(generations) > 0:
        plt.annotate(f"Start: {best_fitness_values[0]}", (generations[0], best_fitness_values[0]), textcoords="offset points", xytext=(0,10), ha='center')
        plt.annotate(f"End: {best_fitness_values[-1]}", (generations[-1], best_fitness_values[-1]), textcoords="offset points", xytext=(0,10), ha='center')

    try:
        plt.savefig(OUTPUT_PLOT_PATH)
        print(f"Fitness plot saved to {OUTPUT_PLOT_PATH}")
    except Exception as e:
        print(f"Error saving plot: {e}")

if __name__ == "__main__":
    # Check if dependent files exist, as sandbox might have been reset
    # The pfoa_core.py script should have created these. If not, this script will fail.
    # For now, we assume the user will ensure these files are present or the previous steps are re-run if needed.
    plot_fitness_history()
    print("Plot generation script finished.")

